chore: protect main branch from local commits

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,4 +4,10 @@
 # https://typicode.github.io/husky/guide.html#with-env-variables
 [ -n "$CI" ] && exit 0
 
+branch="$(git rev-parse --abbrev-ref HEAD)"
+if [ "$branch" = "main" ]; then
+  echo "You can't commit directly to main branch"
+  exit 1
+fi
+
 yarn turbo run --concurrency=1 --filter=[HEAD^1] precommit
